### PR TITLE
#Prepare code for TSE review. A remake of the youtube page

### PR DESCRIPTION
**Pull request by jamezjaz**
This is a remake of the youtube homepage

### CODE REVIEW

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but we need to fix the issues below before moving on ⬇️

- [ ] Consider using the Microverse template for the 'readme' file, and please fill it with the information required on the template, [here](https://github.com/microverseinc/readme-template) you can see it.

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

- [ ] It’s better to delete commented code on your CSS file.  [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) you can see the information about this.

COMMENTLINE

Consider to put `0;` instead of `0px;` on your CSS file. It is not a good practice to put `0px` it is better to put `0;`



- [ ] Consider aligned the 'search bar' to the middle of the navbar.





- [ ] Consider that the three embedded images on the rightmost part of the navbar has to be aligned to the right side of the navbar page, as the original page.



- [ ] Consider matches the appearance of the youtube video player page. 
They should be "appropriately sized and positioned" (as described in the Odin project description). 





- [ ] Consider the positioning of the icons and elements, please make this look like the original page (Icons: 'likes', 'share', 'save'.. has to be in one single line as the original page)





- [ ] Consider fixing the errors on your Validator [Here ](https://validator.w3.org/#validate_by_upload)is the link to do a search for the errors on your project. 



- [ ] Consider the 'footer' is overlapping on your page. Please take care of them so they are displayed properly. 



[OPTIONAL]

- [ ] I encourage you to use the `<main>` tag for the dominant content of the `<body>` of a document

- [ ] You are still missing the comment section. You can include only one or two comments to display it.



- [ ] You could use the same icons on the original page navbar to make your project look better.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by jamezjaz** [comment]
Thank you for this correction

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Your should Pull Request should have a  meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ]  Consider that the three embedded images on the right of the navbar have to be aligned to the rightmost side, as the original page. (as stipulated by previous TSE)#


[OPTIONAL]
##### Video
* [ ] The share should be a button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
### Make changes and submit another code review request.
*Happy coding*

**Comment by Jmagero** [comment]
- Aligned nav bar images
-Updated the README file
-Added a button to share icon

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
# Project Approved :thumbsup:
## Hello Team ,  You have done a great job with this project. :clap:

**Comment by jamezjaz** [comment]
Thank you very much 😊

**Review by kobiyoyo — APPROVED** [review]
Approved

**Comment by jamezjaz** [comment]
Hi,
Please kindly share your full name so I can add you as one of my code
reviewers.
Thank you.

**Comment by jamezjaz** [comment]
Hi Chubi,
I want to submit the project completion form and I couldn’t find Chubi
Adama in the dropdown. Kindly share your full name.
Thank you

**Comment by kobiyoyo** [comment]
DESMOND CHUBIYOJO ADAMA

**Comment by jamezjaz** [comment]
Yes, I later found it. Thank you very much

**Pull request merged**
